title: Risky Satria's Portfolio
description: Footage of My Career
username: Risky Satria
user_description: >-
  I'm a nomad Software Engineer, always searching for the next challenge; no
  task is too scary nor too difficult. Lately I have been immersed in the
  <b>Client Side</b> using React. I used to be a Front End Web Developer and used to be Fullstack Monolith with Codeigniter.
user_title: Product Engineer
email: riskysatria666@gmail.com
exclude:
  - package.json
  - src
  - node_modules
baseurl: ""
url: ""
